// flow-typed signature: 2d4aeab02c2a2319ac1f180c17bdb7e3
// flow-typed version: <<STUB>>/draw-svg-path_vmichaelrhodes/draw-svg-path#2.0.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draw-svg-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draw-svg-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'draw-svg-path/index' {
  declare module.exports: $Exports<'draw-svg-path'>;
}
declare module 'draw-svg-path/index.js' {
  declare module.exports: $Exports<'draw-svg-path'>;
}
