// flow-typed signature: a07803266daffdd171ed225d21ce2c26
// flow-typed version: <<STUB>>/fabric_v^2.3.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fabric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fabric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fabric/build' {
  declare module.exports: any;
}

declare module 'fabric/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'fabric/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'fabric/dist/fabric' {
  declare module.exports: any;
}

declare module 'fabric/test' {
  declare module.exports: any;
}

declare module 'fabric/test/fixtures/test_script' {
  declare module.exports: any;
}

declare module 'fabric/test/lib/canvas_assertions' {
  declare module.exports: any;
}

declare module 'fabric/test/lib/event.simulate' {
  declare module.exports: any;
}

declare module 'fabric/test/node_test_setup' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/activeselection' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/animation' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/brushes' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/canvas_events' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/canvas_static' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/canvas' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/circle' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/collection' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/color' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/ellipse' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/gradient' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/group' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/image_filters' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/image' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/intersection' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/itext_click_behaviour' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/itext_key_behaviour' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/itext' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/line' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/object_geometry' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/object_interactivity' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/object_origin' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/object' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/observable' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/parser' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/path' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/pattern' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/point' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/polygon' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/polyline' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/rect' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/shadow' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/stateful' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/text_to_svg' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/text' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/textbox' {
  declare module.exports: any;
}

declare module 'fabric/test/unit/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fabric/build.js' {
  declare module.exports: $Exports<'fabric/build'>;
}
declare module 'fabric/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'fabric/coverage/lcov-report/prettify'>;
}
declare module 'fabric/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'fabric/coverage/lcov-report/sorter'>;
}
declare module 'fabric/dist/fabric.js' {
  declare module.exports: $Exports<'fabric/dist/fabric'>;
}
declare module 'fabric/test.js' {
  declare module.exports: $Exports<'fabric/test'>;
}
declare module 'fabric/test/fixtures/test_script.js' {
  declare module.exports: $Exports<'fabric/test/fixtures/test_script'>;
}
declare module 'fabric/test/lib/canvas_assertions.js' {
  declare module.exports: $Exports<'fabric/test/lib/canvas_assertions'>;
}
declare module 'fabric/test/lib/event.simulate.js' {
  declare module.exports: $Exports<'fabric/test/lib/event.simulate'>;
}
declare module 'fabric/test/node_test_setup.js' {
  declare module.exports: $Exports<'fabric/test/node_test_setup'>;
}
declare module 'fabric/test/unit/activeselection.js' {
  declare module.exports: $Exports<'fabric/test/unit/activeselection'>;
}
declare module 'fabric/test/unit/animation.js' {
  declare module.exports: $Exports<'fabric/test/unit/animation'>;
}
declare module 'fabric/test/unit/brushes.js' {
  declare module.exports: $Exports<'fabric/test/unit/brushes'>;
}
declare module 'fabric/test/unit/canvas_events.js' {
  declare module.exports: $Exports<'fabric/test/unit/canvas_events'>;
}
declare module 'fabric/test/unit/canvas_static.js' {
  declare module.exports: $Exports<'fabric/test/unit/canvas_static'>;
}
declare module 'fabric/test/unit/canvas.js' {
  declare module.exports: $Exports<'fabric/test/unit/canvas'>;
}
declare module 'fabric/test/unit/circle.js' {
  declare module.exports: $Exports<'fabric/test/unit/circle'>;
}
declare module 'fabric/test/unit/collection.js' {
  declare module.exports: $Exports<'fabric/test/unit/collection'>;
}
declare module 'fabric/test/unit/color.js' {
  declare module.exports: $Exports<'fabric/test/unit/color'>;
}
declare module 'fabric/test/unit/ellipse.js' {
  declare module.exports: $Exports<'fabric/test/unit/ellipse'>;
}
declare module 'fabric/test/unit/gradient.js' {
  declare module.exports: $Exports<'fabric/test/unit/gradient'>;
}
declare module 'fabric/test/unit/group.js' {
  declare module.exports: $Exports<'fabric/test/unit/group'>;
}
declare module 'fabric/test/unit/image_filters.js' {
  declare module.exports: $Exports<'fabric/test/unit/image_filters'>;
}
declare module 'fabric/test/unit/image.js' {
  declare module.exports: $Exports<'fabric/test/unit/image'>;
}
declare module 'fabric/test/unit/intersection.js' {
  declare module.exports: $Exports<'fabric/test/unit/intersection'>;
}
declare module 'fabric/test/unit/itext_click_behaviour.js' {
  declare module.exports: $Exports<'fabric/test/unit/itext_click_behaviour'>;
}
declare module 'fabric/test/unit/itext_key_behaviour.js' {
  declare module.exports: $Exports<'fabric/test/unit/itext_key_behaviour'>;
}
declare module 'fabric/test/unit/itext.js' {
  declare module.exports: $Exports<'fabric/test/unit/itext'>;
}
declare module 'fabric/test/unit/line.js' {
  declare module.exports: $Exports<'fabric/test/unit/line'>;
}
declare module 'fabric/test/unit/object_geometry.js' {
  declare module.exports: $Exports<'fabric/test/unit/object_geometry'>;
}
declare module 'fabric/test/unit/object_interactivity.js' {
  declare module.exports: $Exports<'fabric/test/unit/object_interactivity'>;
}
declare module 'fabric/test/unit/object_origin.js' {
  declare module.exports: $Exports<'fabric/test/unit/object_origin'>;
}
declare module 'fabric/test/unit/object.js' {
  declare module.exports: $Exports<'fabric/test/unit/object'>;
}
declare module 'fabric/test/unit/observable.js' {
  declare module.exports: $Exports<'fabric/test/unit/observable'>;
}
declare module 'fabric/test/unit/parser.js' {
  declare module.exports: $Exports<'fabric/test/unit/parser'>;
}
declare module 'fabric/test/unit/path.js' {
  declare module.exports: $Exports<'fabric/test/unit/path'>;
}
declare module 'fabric/test/unit/pattern.js' {
  declare module.exports: $Exports<'fabric/test/unit/pattern'>;
}
declare module 'fabric/test/unit/point.js' {
  declare module.exports: $Exports<'fabric/test/unit/point'>;
}
declare module 'fabric/test/unit/polygon.js' {
  declare module.exports: $Exports<'fabric/test/unit/polygon'>;
}
declare module 'fabric/test/unit/polyline.js' {
  declare module.exports: $Exports<'fabric/test/unit/polyline'>;
}
declare module 'fabric/test/unit/rect.js' {
  declare module.exports: $Exports<'fabric/test/unit/rect'>;
}
declare module 'fabric/test/unit/shadow.js' {
  declare module.exports: $Exports<'fabric/test/unit/shadow'>;
}
declare module 'fabric/test/unit/stateful.js' {
  declare module.exports: $Exports<'fabric/test/unit/stateful'>;
}
declare module 'fabric/test/unit/text_to_svg.js' {
  declare module.exports: $Exports<'fabric/test/unit/text_to_svg'>;
}
declare module 'fabric/test/unit/text.js' {
  declare module.exports: $Exports<'fabric/test/unit/text'>;
}
declare module 'fabric/test/unit/textbox.js' {
  declare module.exports: $Exports<'fabric/test/unit/textbox'>;
}
declare module 'fabric/test/unit/util.js' {
  declare module.exports: $Exports<'fabric/test/unit/util'>;
}
