// flow-typed signature: 5a5264fe75776f3e89e108d7c47ed8a7
// flow-typed version: <<STUB>>/svg-path-properties_v^0.4.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-path-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-path-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-path-properties/build/path-properties' {
  declare module.exports: any;
}

declare module 'svg-path-properties/build/path-properties.min' {
  declare module.exports: any;
}

declare module 'svg-path-properties/src/arc' {
  declare module.exports: any;
}

declare module 'svg-path-properties/src/bezier' {
  declare module.exports: any;
}

declare module 'svg-path-properties/src/linear' {
  declare module.exports: any;
}

declare module 'svg-path-properties/src/parse' {
  declare module.exports: any;
}

declare module 'svg-path-properties/src/path-properties' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-path-properties/build/path-properties.js' {
  declare module.exports: $Exports<'svg-path-properties/build/path-properties'>;
}
declare module 'svg-path-properties/build/path-properties.min.js' {
  declare module.exports: $Exports<'svg-path-properties/build/path-properties.min'>;
}
declare module 'svg-path-properties/index' {
  declare module.exports: $Exports<'svg-path-properties'>;
}
declare module 'svg-path-properties/index.js' {
  declare module.exports: $Exports<'svg-path-properties'>;
}
declare module 'svg-path-properties/src/arc.js' {
  declare module.exports: $Exports<'svg-path-properties/src/arc'>;
}
declare module 'svg-path-properties/src/bezier.js' {
  declare module.exports: $Exports<'svg-path-properties/src/bezier'>;
}
declare module 'svg-path-properties/src/linear.js' {
  declare module.exports: $Exports<'svg-path-properties/src/linear'>;
}
declare module 'svg-path-properties/src/parse.js' {
  declare module.exports: $Exports<'svg-path-properties/src/parse'>;
}
declare module 'svg-path-properties/src/path-properties.js' {
  declare module.exports: $Exports<'svg-path-properties/src/path-properties'>;
}
